---
version: 1.0.0
name: SMLIGHT SLZB-07 Programmer
slug: smlight_slzb-07_programmer
description: Program the manufacturer and vendor strings to a SLZB-07's CP2102N chip
url: "https://github.com/tl-sl/smlight_programmer/tree/master/smlight_slzb07_programmer"
image: darkxst/{arch}-addon-smlight_slzb07_programmer
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
stage: experimental
startup: once
boot: manual
hassio_api: true
init: false
usb: true
options:
  device: null
schema:
  device: device(subsystem=tty)
  advanced:
    manufacturer: str
    product: str
