---
# yamllint disable rule:truthy
name: Lint

env:
  HADOLINT_VERSION: v1.17.2
  SHELLCHECK_OPTS: -e SC1008 -s bash

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: hadolint
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run linter
        id: changed_files
        run: |
          shopt -s globstar
          for dockerfile in **/Dockerfile; do
            echo "Linting: $dockerfile"
            docker run --rm -i \
              -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
              hadolint/hadolint:${{ env.HADOLINT_VERSION }} < "$dockerfile"
          done

  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run linter
        uses: ludeeus/action-shellcheck@2.0.0
